# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Admin.find_or_create_by!(id: 1, email: "test@test") do |admin|
    admin.password = "test10"
end

Prefecture.find_or_create_by!(id: 1, name: '北海道')
Prefecture.find_or_create_by!(id: 2, name: '青森')
Prefecture.find_or_create_by!(id: 3, name: '秋田')
Prefecture.find_or_create_by!(id: 4, name: '岩手')
Prefecture.find_or_create_by!(id: 5, name: '宮城')
Prefecture.find_or_create_by!(id: 6, name: '山形')
Prefecture.find_or_create_by!(id: 7, name: '福島')
Prefecture.find_or_create_by!(id: 8, name: '栃木')
Prefecture.find_or_create_by!(id: 9, name: '茨城')
Prefecture.find_or_create_by!(id: 10, name: '群馬')
Prefecture.find_or_create_by!(id: 11, name: '埼玉')
Prefecture.find_or_create_by!(id: 12, name: '千葉')
Prefecture.find_or_create_by!(id: 13, name: '東京')
Prefecture.find_or_create_by!(id: 14, name: '神奈川')
Prefecture.find_or_create_by!(id: 15, name: '新潟')
Prefecture.find_or_create_by!(id: 16, name: '富山')
Prefecture.find_or_create_by!(id: 17, name: '石川')
Prefecture.find_or_create_by!(id: 18, name: '福井')
Prefecture.find_or_create_by!(id: 19, name: '山梨')
Prefecture.find_or_create_by!(id: 20, name: '長野')
Prefecture.find_or_create_by!(id: 21, name: '岐阜')
Prefecture.find_or_create_by!(id: 22, name: '静岡')
Prefecture.find_or_create_by!(id: 23, name: '愛知')
Prefecture.find_or_create_by!(id: 24, name: '三重')
Prefecture.find_or_create_by!(id: 25, name: '滋賀')
Prefecture.find_or_create_by!(id: 26, name: '京都')
Prefecture.find_or_create_by!(id: 27, name: '大阪')
Prefecture.find_or_create_by!(id: 28, name: '兵庫')
Prefecture.find_or_create_by!(id: 29, name: '奈良')
Prefecture.find_or_create_by!(id: 30, name: '和歌山')
Prefecture.find_or_create_by!(id: 31, name: '鳥取')
Prefecture.find_or_create_by!(id: 32, name: '島根')
Prefecture.find_or_create_by!(id: 33, name: '岡山')
Prefecture.find_or_create_by!(id: 34, name: '広島')
Prefecture.find_or_create_by!(id: 35, name: '山口')
Prefecture.find_or_create_by!(id: 36, name: '徳島')
Prefecture.find_or_create_by!(id: 37, name: '香川')
Prefecture.find_or_create_by!(id: 38, name: '愛媛')
Prefecture.find_or_create_by!(id: 39, name: '高知')
Prefecture.find_or_create_by!(id: 40, name: '福岡')
Prefecture.find_or_create_by!(id: 41, name: '佐賀')
Prefecture.find_or_create_by!(id: 42, name: '長崎')
Prefecture.find_or_create_by!(id: 43, name: '熊本')
Prefecture.find_or_create_by!(id: 44, name: '大分')
Prefecture.find_or_create_by!(id: 45, name: '宮崎')
Prefecture.find_or_create_by!(id: 46, name: '鹿児島')
Prefecture.find_or_create_by!(id: 47, name: '沖縄')

Category.find_or_create_by!(id: 1, name: '男子6人制')
Category.find_or_create_by!(id: 2, name: '男子9人制')
Category.find_or_create_by!(id: 3, name: '女子6人制')
Category.find_or_create_by!(id: 4, name: '女子9人制')
Category.find_or_create_by!(id: 5, name: '混合')
Category.find_or_create_by!(id: 6, name: 'ビーチ2人制')
Category.find_or_create_by!(id: 7, name: 'ビーチ4人制')


